Fixed bug with view panel, implemented stricter range for datetime and removed styling when list cell selected.
AY2021S1-CS2103T-F11-2/tp pull request #192
Opened 2020-11-03 07:43 UTC by shadowezz

2020-11-03 13:29 UTC, chrystalquek requested changes
When adding/editing an item, currently not automatically showing in view panel
Not sure about other commands

2020-11-03 13:29 UTC, chrystalquek commented on src/main/java/seedu/address/model/util/DateTime.java
> +            Date earliestDate = df.parse(EARLIEST_DATE_STRING);
can it be EARLIEST_DATE instead of EARLIEST_DATE_STRING? so don't need to parse each time
also why Date and not LocalDateTime?

2020-11-03 13:29 UTC, chrystalquek commented on src/main/java/seedu/address/model/util/DateTime.java
> +            if (date.before(earliestDate)) {
just return !date.before(earliestDate)

2020-11-03 13:29 UTC, chrystalquek commented on src/main/java/seedu/address/model/util/DateTime.java
> +                    + "and should be within the calendar range starting from year 2019. "
update in docs?

2020-11-03 13:45 UTC, shadowezz commented on src/main/java/seedu/address/model/util/DateTime.java
> +                    + "and should be within the calendar range starting from year 2019. "
yup done

2020-11-03 13:48 UTC, shadowezz commented on src/main/java/seedu/address/model/util/DateTime.java
> +                    + "and should be within the calendar range starting from year 2019. "
its in my other pr

2020-11-04 09:10 UTC, chrystalquek approved these changes
LGTM

2020-11-04 09:11 UTC, merged